version: '3.8'

networks:
  lan_access:
    driver: bridge

volumes:
  pgdata: {}
  assets: {}

services:
  db:
    hostname: db
    image: postgis/postgis:15-3.3-alpine
    shm_size: 512m
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: unless-stopped
    networks:
      - lan_access
    ports:
      - "${DB_HOST_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    hostname: app
    image: jpo:latest
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - SECRET_KEY_BASE
      - RAILS_ENV=${ENV}
      - POSTGRES_HOST=db
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: "unless-stopped"
    depends_on:
      - db
      - web
    networks:
      - lan_access
    ports:
      - ${APP_HOST_PORT}:3000
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/app # dev mode; comment this line in production!
      - assets:/app/public

  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: "unless-stopped"
    ports:
      - 80:80
    volumes:
      - assets:/var/www/public:ro
    networks:
      - lan_access